format:
  html: {toc: true, toc-depth: 4, theme: cosmo}
  revealjs: {theme: solarized, navigation-mode: vertical, transition: slide, background-transition: fade, incremental: true}
project: {type: book}
book:
  chapters:
  - index.qmd
  - quickstart.qmd
  - gotchas.qmd
  - packages.qmd
  - part: Tutorials for scientists
    chapters: [for_scientists.index.qmd, for_scientists.cavity_physics.qmd]
  - part: Tutorials for developers
    chapters: [for_developers.index.qmd]
  - faq.qmd
  title: Wolframite Documentation
